### ISSUE TITLE
[BUG] Releases are not working

### ISSUE THREAD

**Issue by trhgquan** [khongsomeo/GPA-OOP#69]
# Bug report

### 3. If the bug happened in an issue before but is still not fixed yet, mention the issue here:

(List of issues created).

### 4. Short describe:

None of the binary builds working. Maybe we should take a look at compiler options (linking static libs).

### 5. Proof:

(Insert images, videos or describe how can we re-create that bug).

### 6. Team mentioning:

(Mention the project's response team here).

**Comment by hwangswan** [comment]
To be clear: only Windows version doesn't working very well.
